//
//  HomeInterfaces.swift
//  BTCUSDOrderBook
//
//  Created by Vedran Burojevic on 24/08/2019.
//  Copyright (c) 2019 Caffeinated Code. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum HomeNavigationOption {
}

protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to option: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func setup(with output: HomeViewOutput) -> HomeViewInput
}

protocol HomeInteractorInterface: InteractorInterface {
    var isConnected: Observable<Bool> { get }
    var ticker: Observable<Ticker> { get }
    var orderBookSnapshot: Observable<OrderBookSnapshot> { get }
    var orderBookUpdate: Observable<OrderBookUpdate> { get }
    
    func connect()
}

struct HomeViewOutput {
}

struct HomeViewInput {
    let headerItem: Driver<HomeHeaderViewItem>
    let isHeaderIndicatorAnimating: Driver<Bool>
    let isHeaderHidden: Driver<Bool>
    
    let cellItems: Driver<[HomeCellItem]>
    let isTableIndicatorAnimating: Driver<Bool>
    let isTableHidden: Driver<Bool>
}
