//
//  HomeInteractor.swift
//  BTCUSDOrderBook
//
//  Created by Vedran Burojevic on 24/08/2019.
//  Copyright (c) 2019 Caffeinated Code. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
}
